version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # generate test code file
      - run:
          name: Generate Test Code Files
          command: ./node_modules/.bin/truffle run mythx A.sol MetaCoin.sol

      # run security tests
      - run:
          name: Run Security Tests
          command: npm run test:security
      
      # run coverall
      #- run:
      #    name: Coverage report
      #    command: ./node_modules/.bin/lerna run coverage 
